#!/bin/bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

CACHYOS_PACKAGES=(
  base-devel
  bash
  bash-completion
  zsh
  oh-my-zsh-git
  zsh-theme-powerlevel10k
  zsh-autosuggestions
  zsh-history-substring-search
  zsh-syntax-highlighting
  fish
  git
  git-lfs
  openssh
  github-cli
  lazygit
  fzf
  ripgrep
  fd
  expac
  ncurses
  neovim
  tmux
  alacritty
  clang
)

link() {
  local src="$1"
  local dest="$2"

  if [ -L "$dest" ]; then
    local current
    current="$(readlink "$dest")"
    if [ "$current" = "$src" ]; then
      echo "  [ok] $dest -> $src"
      return
    fi
    echo "  [..] Updating symlink $dest"
    rm "$dest"
  elif [ -e "$dest" ]; then
    echo "  [..] Backing up $dest to ${dest}.bak"
    mv "$dest" "${dest}.bak"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  echo "  [ok] $dest -> $src"
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-N}"
  local answer

  read -rp "$prompt" answer
  if [ -z "$answer" ]; then
    answer="$default"
  fi

  [[ "$answer" =~ ^[Yy]$ ]]
}

install_cachyos_packages() {
  if ! command -v pacman &>/dev/null; then
    echo "--- CachyOS packages ---"
    echo "  [skip] pacman not found"
    return
  fi

  echo "--- CachyOS packages ---"
  if ! prompt_yes_no "Install/update CachyOS packages with pacman? [Y/n] " "Y"; then
    echo "  [skip] package install"
    return
  fi

  sudo pacman -Syu --needed --noconfirm "${CACHYOS_PACKAGES[@]}"

  if command -v git-lfs &>/dev/null; then
    git lfs install
  fi
}

set_default_shell() {
  local shell_name="$1"
  local shell_path

  if ! command -v "$shell_name" &>/dev/null; then
    return
  fi

  shell_path="$(command -v "$shell_name")"
  if [ "${SHELL:-}" = "$shell_path" ]; then
    echo "  [ok] default shell is $shell_name"
    return
  fi

  if ! prompt_yes_no "Set $shell_name as your default shell? [y/N] " "N"; then
    echo "  [skip] default shell unchanged"
    return
  fi

  if ! grep -Fxq "$shell_path" /etc/shells; then
    echo "$shell_path" | sudo tee -a /etc/shells >/dev/null
  fi

  chsh -s "$shell_path"
  echo "  [ok] default shell set to $shell_path"
}

remove_legacy_bash_link() {
  local src="$1"
  local dest="$2"

  if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
    rm "$dest"
    echo "  [ok] removed old bash symlink $dest"
  fi
}

first_existing_path() {
  local candidate

  for candidate in "$@"; do
    if [ -e "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  return 1
}

write_zsh_path() {
  local name="$1"
  local value="$2"

  if [ -n "$value" ]; then
    printf 'export %s=%q\n' "$name" "$value"
  fi
}

write_oh_my_zsh_rc() {
  local dest="$HOME/.oh-my-zsh.rc"
  local zsh_dir
  local fzf_base
  local p10k_theme
  local autosuggestions
  local history_substring_search
  local syntax_highlighting
  local pkgfile_handler
  local sources=()

  echo "--- Oh My Zsh local config ---"

  zsh_dir="$(first_existing_path /usr/share/oh-my-zsh "$HOME/.oh-my-zsh" || true)"
  fzf_base="$(first_existing_path /usr/share/fzf "$HOME/.fzf" || true)"
  p10k_theme="$(first_existing_path \
    /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme \
    /usr/share/powerlevel10k/powerlevel10k.zsh-theme \
    "$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" || true)"
  autosuggestions="$(first_existing_path \
    /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh \
    "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" || true)"
  history_substring_search="$(first_existing_path \
    /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh \
    "$HOME/.oh-my-zsh/custom/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh" || true)"
  syntax_highlighting="$(first_existing_path \
    /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
    "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" || true)"
  pkgfile_handler="$(first_existing_path /usr/share/doc/pkgfile/command-not-found.zsh || true)"

  [ -z "$autosuggestions" ] || sources+=("$autosuggestions")
  [ -z "$history_substring_search" ] || sources+=("$history_substring_search")
  [ -z "$pkgfile_handler" ] || sources+=("$pkgfile_handler")
  [ -z "$syntax_highlighting" ] || sources+=("$syntax_highlighting")

  if [ -e "$dest" ] && ! grep -Fq "Generated by dotfiles install.sh" "$dest"; then
    echo "  [..] Backing up $dest to ${dest}.bak"
    mv "$dest" "${dest}.bak"
  fi

  {
    printf '# Generated by dotfiles install.sh; keep host-specific zsh paths here.\n'
    write_zsh_path ZSH "$zsh_dir"
    write_zsh_path FZF_BASE "$fzf_base"
    write_zsh_path POWERLEVEL10K_THEME "$p10k_theme"
    printf 'typeset -ga DOTFILES_ZSH_EXTRA_SOURCES=(\n'
    if ((${#sources[@]} > 0)); then
      printf '  %q\n' "${sources[@]}"
    fi
    printf ')\n'
  } >"$dest"

  echo "  [ok] wrote $dest"
}

install_terminal_configs() {
  local shell_choice

  echo "--- Terminal shells ---"
  read -rp "Install shell config? [fish/bash/zsh/both/all/none] " shell_choice
  shell_choice="${shell_choice:-fish}"

  case "$shell_choice" in
    fish)
      link "$DOTFILES_DIR/terminal/fish" "$HOME/.config/fish"
      set_default_shell fish
      ;;
    bash)
      link "$DOTFILES_DIR/terminal/bash/.bashrc" "$HOME/.bashrc"
      link "$DOTFILES_DIR/terminal/bash/.bash_profile" "$HOME/.bash_profile"
      link "$DOTFILES_DIR/terminal/bash/.profile" "$HOME/.profile"
      set_default_shell bash
      ;;
    zsh)
      write_oh_my_zsh_rc
      link "$DOTFILES_DIR/terminal/zsh/.zshrc" "$HOME/.zshrc"
      link "$DOTFILES_DIR/terminal/zsh/.p10k.zsh" "$HOME/.p10k.zsh"
      set_default_shell zsh
      ;;
    both)
      link "$DOTFILES_DIR/terminal/fish" "$HOME/.config/fish"
      link "$DOTFILES_DIR/terminal/bash/.bashrc" "$HOME/.bashrc"
      link "$DOTFILES_DIR/terminal/bash/.bash_profile" "$HOME/.bash_profile"
      link "$DOTFILES_DIR/terminal/bash/.profile" "$HOME/.profile"
      echo "  [info] Fish and Bash configs installed; choose your default shell next."
      read -rp "Default shell? [fish/bash/skip] " default_shell
      case "${default_shell:-fish}" in
        fish) set_default_shell fish ;;
        bash) set_default_shell bash ;;
        skip) echo "  [skip] default shell unchanged" ;;
        *) echo "  [skip] unknown default shell choice: $default_shell" ;;
      esac
      ;;
    all)
      link "$DOTFILES_DIR/terminal/fish" "$HOME/.config/fish"
      link "$DOTFILES_DIR/terminal/bash/.bashrc" "$HOME/.bashrc"
      link "$DOTFILES_DIR/terminal/bash/.bash_profile" "$HOME/.bash_profile"
      link "$DOTFILES_DIR/terminal/bash/.profile" "$HOME/.profile"
      write_oh_my_zsh_rc
      link "$DOTFILES_DIR/terminal/zsh/.zshrc" "$HOME/.zshrc"
      link "$DOTFILES_DIR/terminal/zsh/.p10k.zsh" "$HOME/.p10k.zsh"
      echo "  [info] Fish, Bash, and Zsh configs installed; choose your default shell next."
      read -rp "Default shell? [fish/bash/zsh/skip] " default_shell
      case "${default_shell:-fish}" in
        fish) set_default_shell fish ;;
        bash) set_default_shell bash ;;
        zsh) set_default_shell zsh ;;
        skip) echo "  [skip] default shell unchanged" ;;
        *) echo "  [skip] unknown default shell choice: $default_shell" ;;
      esac
      ;;
    none)
      echo "  [skip] shell config"
      ;;
    *)
      echo "  [skip] unknown shell config choice: $shell_choice"
      ;;
  esac
}

install_tmux_plugin_manager() {
  local tpm_dir="$HOME/.tmux/plugins/tpm"

  echo "--- Tmux plugins ---"
  if [ -d "$tpm_dir/.git" ]; then
    echo "  [ok] TPM already installed"
  elif ! command -v git &>/dev/null; then
    echo "  [skip] git not found; install git before installing TPM"
    return
  elif ! prompt_yes_no "Install TPM for tmux plugins? [Y/n] " "Y"; then
    echo "  [skip] TPM install"
    return
  else
    mkdir -p "$(dirname "$tpm_dir")"
    git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
    echo "  [ok] TPM installed"
  fi

  if [ -x "$tpm_dir/bin/install_plugins" ]; then
    "$tpm_dir/bin/install_plugins" || echo "  [!!] Failed to install tmux plugins"
  fi
}

echo "=== Dotfiles installer ==="
echo "Source: $DOTFILES_DIR"
echo ""

install_cachyos_packages

install_terminal_configs

# Legacy shell cleanup
echo "--- Legacy Bash cleanup ---"
remove_legacy_bash_link "$DOTFILES_DIR/bash/.bashrc" "$HOME/.bashrc"
remove_legacy_bash_link "$DOTFILES_DIR/bash/.bash_profile" "$HOME/.bash_profile"
remove_legacy_bash_link "$DOTFILES_DIR/bash/.profile" "$HOME/.profile"
remove_legacy_bash_link "$DOTFILES_DIR/bash/.bash_completion" "$HOME/.bash_completion"
remove_legacy_bash_link "$DOTFILES_DIR/fish" "$HOME/.config/fish"

# Neovim
echo "--- Neovim ---"
link "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"

# Tmux
echo "--- Tmux ---"
link "$DOTFILES_DIR/tmux/tmux.conf" "$HOME/.tmux.conf"
install_tmux_plugin_manager

# Git
echo "--- Git ---"
link "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"

# Alacritty
echo "--- Alacritty ---"
link "$DOTFILES_DIR/alacritty" "$HOME/.config/alacritty"

# C/C++ user-level defaults
echo "--- C/C++ ---"
if [ -f "$DOTFILES_DIR/.clangd" ]; then
  link "$DOTFILES_DIR/.clangd" "$HOME/.clangd"
fi
if [ -f "$DOTFILES_DIR/.clang-format" ]; then
  link "$DOTFILES_DIR/.clang-format" "$HOME/.clang-format"
fi

echo ""
echo "=== Symlinks created ==="
echo "  terminal shell config, nvim, tmux, git, alacritty, clangd, clang-format"

# Offer to install Neovim plugin dependencies
if [ -x "$DOTFILES_DIR/nvim/install-deps.sh" ]; then
  echo ""
  read -rp "Install Neovim plugin dependencies? [y/N] " answer
  if [[ "$answer" =~ ^[Yy]$ ]]; then
    "$DOTFILES_DIR/nvim/install-deps.sh"
  fi
fi
