# Enable Powerlevel10k instant prompt. Keep this near the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Machine-local paths are generated by install.sh.
[[ ! -r "$HOME/.oh-my-zsh.rc" ]] || source "$HOME/.oh-my-zsh.rc"

: "${ZSH:=/usr/share/oh-my-zsh}"
: "${FZF_BASE:=/usr/share/fzf}"
: "${POWERLEVEL10K_THEME:=/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme}"

typeset -ga DOTFILES_ZSH_EXTRA_SOURCES
if (( ${#DOTFILES_ZSH_EXTRA_SOURCES[@]} == 0 )); then
  DOTFILES_ZSH_EXTRA_SOURCES=(
    /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
    /usr/share/doc/pkgfile/command-not-found.zsh
    /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  )
fi

export EDITOR="nvim"
export VISUAL="$EDITOR"
export FZF_BASE

HISTFILE="${HISTFILE:-$HOME/.zsh_history}"
HISTSIZE="${HISTSIZE:-10000}"
SAVEHIST="${SAVEHIST:-10000}"
setopt append_history
setopt extended_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt share_history

DISABLE_MAGIC_FUNCTIONS="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HISTORY_IGNORE="(&|[bf]g|c|clear|history|exit|q|pwd|* --help)"
plugins=(git fzf extract compleat command-not-found)

if [[ -r "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
else
  print -u2 "oh-my-zsh not found at $ZSH; run ./install.sh or update ~/.oh-my-zsh.rc"
fi

_dotfiles_source() {
  [[ ! -r "$1" ]] || source "$1"
}

_dotfiles_source "$POWERLEVEL10K_THEME"

for source_file in "${DOTFILES_ZSH_EXTRA_SOURCES[@]}"; do
  _dotfiles_source "$source_file"
done

alias make='make -j$(nproc)'
alias ninja='ninja -j$(nproc)'
alias n="ninja"
alias c="clear"
alias rmpkg="sudo pacman -Rsn"
alias cleanch="sudo pacman -Scc"
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias update="sudo pacman -Syu"
alias apt="man pacman"
alias apt-get="man pacman"
alias please="sudo"
alias tb="nc termbin.com 9999"
alias cleanup="cleanup_orphans"
alias jctl="journalctl -p 3 -xb"
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias git="nocorrect git"
alias vim="nvim"

cleanup_orphans() {
  local orphans
  orphans=("${(@f)$(pacman -Qtdq 2>/dev/null)}")

  if (( ${#orphans[@]} == 0 )); then
    print "No orphaned packages."
    return 0
  fi

  sudo pacman -Rsn "${orphans[@]}"
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -r "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export PLANTUML_JAR_PATH=/usr/share/java/plantuml/plantuml.jar

unfunction _dotfiles_source 2>/dev/null || true
